package space.zeroxv6.kotlin_mls

import android.content.Context
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import uniffi.android_openmls.MlsClient
import uniffi.android_openmls.MlsException
import uniffi.android_openmls.MemberInfo

/**
 * Kotlin wrapper for OpenMLS providing end-to-end encrypted group messaging
 * via the MLS protocol (RFC 9420).
 *
 * ## Lifecycle
 * 1. Create an [MlsService] instance.
 * 2. Call [createIdentity] once to generate cryptographic keys.
 * 3. Use [generateKeyPackage] each time you want to be added to a group.
 * 4. Create or join groups, then encrypt/decrypt messages.
 *
 * ## Thread safety
 * All public methods are suspending and dispatched on [Dispatchers.IO].
 * The underlying Rust layer uses a Mutex internally.
 *
 * @param context  Android context (used only for [Context.getFilesDir]).
 * @param storageName  Unique storage folder name; allows multiple users on
 *                     the same device (useful for testing).
 */
class MlsService(context: Context, storageName: String = "mls_storage") {

    private val client: MlsClient by lazy {
        val dbPath = context.filesDir.absolutePath + "/" + storageName
        MlsClient(dbPath)
    }

    // ── Identity ───────────────────────────────────────────────────────

    /**
     * Creates (or recreates) this client's cryptographic identity.
     *
     * **Must** be called before any group operations.
     *
     * @param name  Display name bound to the credential.
     * @return The identity name on success.
     */
    suspend fun createIdentity(name: String): String = withContext(Dispatchers.IO) {
        try {
            client.createIdentity(name)
        } catch (e: MlsException) {
            throw MlsServiceException("Failed to create identity", e)
        }
    }

    /**
     * Generates a fresh, single-use key package for the current identity.
     *
     * Call this each time you need to be added to a new group.
     * Key packages should **not** be reused across groups.
     *
     * @return Hex-encoded key package.
     */
    suspend fun generateKeyPackage(): String = withContext(Dispatchers.IO) {
        try {
            client.generateKeyPackage()
        } catch (e: MlsException) {
            throw MlsServiceException("Failed to generate key package", e)
        }
    }

    /**
     * Returns `true` if [createIdentity] has been called (or an identity
     * was restored from disk).
     */
    suspend fun hasIdentity(): Boolean = withContext(Dispatchers.IO) {
        client.hasIdentity()
    }

    // ── Group lifecycle ────────────────────────────────────────────────

    /**
     * Creates a new MLS group.
     *
     * @return Hex-encoded group ID (auto-generated by OpenMLS).
     */
    suspend fun createGroup(groupId: String = ""): String = withContext(Dispatchers.IO) {
        try {
            client.createGroup(groupId)
        } catch (e: MlsException) {
            throw MlsServiceException("Failed to create group", e)
        }
    }

    /**
     * Adds a new member to an existing group.
     *
     * @param groupId        Target group.
     * @param keyPackageHex  The new member's key package (from [generateKeyPackage]).
     * @return JSON: `{"commit":"<hex>","welcome":"<hex>"}`.
     *   - **commit** → send to all *existing* members via [processCommit].
     *   - **welcome** → send to the *new* member via [processWelcome].
     */
    suspend fun addMember(groupId: String, keyPackageHex: String): String =
        withContext(Dispatchers.IO) {
            try {
                client.addMember(groupId, keyPackageHex)
            } catch (e: MlsException) {
                throw MlsServiceException("Failed to add member to group $groupId", e)
            }
        }

    /**
     * Removes a member from a group by their leaf index.
     *
     * Use [getMembers] to discover leaf indices.
     *
     * @return JSON: `{"commit":"<hex>"}` — broadcast to remaining members.
     */
    suspend fun removeMember(groupId: String, memberIndex: UInt): String =
        withContext(Dispatchers.IO) {
            try {
                client.removeMember(groupId, memberIndex)
            } catch (e: MlsException) {
                throw MlsServiceException("Failed to remove member from group $groupId", e)
            }
        }

    /**
     * Rotates this member's leaf key material (post-compromise security).
     *
     * Even if your keys were previously compromised, messages sent after
     * a successful self-update are secure again.
     *
     * @return JSON: `{"commit":"<hex>"}` — broadcast to all other members.
     */
    suspend fun selfUpdate(groupId: String): String = withContext(Dispatchers.IO) {
        try {
            client.selfUpdate(groupId)
        } catch (e: MlsException) {
            throw MlsServiceException("Failed to self-update in group $groupId", e)
        }
    }

    /**
     * Processes a Welcome message to join a group.
     *
     * @param welcomeHex  Hex-encoded Welcome from the group admin.
     * @return The group ID you've joined.
     */
    suspend fun processWelcome(welcomeHex: String): String = withContext(Dispatchers.IO) {
        try {
            val groupId = client.processWelcome(welcomeHex)
            client.saveState()
            groupId
        } catch (e: MlsException) {
            throw MlsServiceException("Failed to process Welcome message", e)
        }
    }

    /**
     * Processes a Commit from another member (e.g. add/remove/update).
     *
     * All existing members **must** process commits to stay in sync.
     */
    suspend fun processCommit(groupId: String, commitHex: String): Unit =
        withContext(Dispatchers.IO) {
            try {
                client.processCommit(groupId, commitHex)
                client.saveState()
            } catch (e: MlsException) {
                throw MlsServiceException("Failed to process commit for group $groupId", e)
            }
        }

    // ── Messaging ──────────────────────────────────────────────────────

    /**
     * Encrypts a plaintext message for the group.
     *
     * @return Hex-encoded ciphertext to broadcast to **all** group members.
     */
    suspend fun encrypt(groupId: String, plaintext: String): String =
        withContext(Dispatchers.IO) {
            try {
                client.encryptMessage(groupId, plaintext)
            } catch (e: MlsException) {
                throw MlsServiceException("Failed to encrypt message for group $groupId", e)
            }
        }

    /**
     * Decrypts an application message from the group.
     *
     * If the message is actually a Commit or Proposal it will be
     * processed internally, and an [MlsServiceException] is thrown to
     * inform the caller that this was not an application message.
     *
     * @return The decrypted plaintext.
     */
    suspend fun decrypt(groupId: String, ciphertextHex: String): String =
        withContext(Dispatchers.IO) {
            try {
                val result = client.decryptMessage(groupId, ciphertextHex)
                client.saveState()
                result
            } catch (e: MlsException) {
                throw MlsServiceException("Failed to decrypt message for group $groupId", e)
            }
        }

    // ── Group queries ──────────────────────────────────────────────────

    /**
     * Lists hex-encoded IDs of all groups currently in memory.
     */
    suspend fun listActiveGroups(): List<String> = withContext(Dispatchers.IO) {
        try {
            client.listActiveGroups()
        } catch (e: Exception) {
            emptyList()
        }
    }

    /**
     * Returns JSON with group metadata: `group_id`, `epoch`, `member_count`.
     */
    suspend fun getGroupInfo(groupId: String): String = withContext(Dispatchers.IO) {
        try {
            client.getGroupInfo(groupId)
        } catch (e: MlsException) {
            throw MlsServiceException("Failed to get group info for $groupId", e)
        }
    }

    /**
     * Returns the list of members in the group with their leaf index
     * and credential identity bytes.
     */
    suspend fun getMembers(groupId: String): List<MemberInfo> = withContext(Dispatchers.IO) {
        try {
            client.getMembers(groupId)
        } catch (e: MlsException) {
            throw MlsServiceException("Failed to get members for group $groupId", e)
        }
    }

    // ── Persistence ────────────────────────────────────────────────────

    /**
     * Explicitly saves ALL state to disk: identity keys, group secrets,
     * ratchet trees — everything needed to resume after a cold restart.
     *
     * Writes two files:
     * - `state.json`: identity metadata and group list
     * - `openmls_store.json`: full OpenMLS cryptographic key store
     *
     * State is also auto-saved after [processWelcome], [processCommit],
     * and [decrypt].
     */
    suspend fun save(): Unit = withContext(Dispatchers.IO) {
        try {
            client.saveState()
        } catch (e: MlsException) {
            throw MlsServiceException("Failed to save state", e)
        }
    }

    /**
     * Reloads the full persisted state from disk, including identity
     * keys and group recovery.
     *
     * Called automatically by the constructor; you typically don't need
     * to call this manually.
     */
    suspend fun load(): Unit = withContext(Dispatchers.IO) {
        try {
            client.loadState()
        } catch (e: MlsException) {
            throw MlsServiceException("Failed to load state", e)
        }
    }

    /**
     * Lists group IDs that were saved in a previous session.
     * After [load], these groups are fully restored and usable.
     */
    suspend fun listSavedGroups(): List<String> = withContext(Dispatchers.IO) {
        try {
            client.listSavedGroups()
        } catch (e: MlsException) {
            emptyList()
        }
    }
}

/**
 * Wrapper around errors originating from the native MLS layer.
 */
class MlsServiceException : Exception {
    constructor(message: String, cause: Throwable? = null) : super(message, cause)

    constructor(message: String, mlsException: MlsException) : super(
        "$message: ${mlsException.toString()}",
        mlsException
    )
}